spring:
  application:
    name: sleepy-consumer
  kafka:
    bootstrap-servers: "localhost:9092"
    consumer:
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
    properties:
      schema.registry.url: http://localhost:8081
  datasource:
    url: "jdbc:postgresql://localhost:5432/kafka_connect"
    username: "kafka_connect_user"
    password: "kafka_connect_password"
logging:
  level:
    org.apache.kafka.clients.consumer: warn
    io.confluent.kafka.serializers: warn